# Generated by Django 5.2.11 on 2026-03-11 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors', '0006_alter_connectoraccount_source'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('google_fit', 'Google Fit'), ('asana', 'Asana'), ('todoist', 'Todoist'), ('habitica', 'Habitica'), ('jira', 'Jira')], max_length=50)),
                ('source_entity_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_status', models.CharField(blank=True, max_length=100, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('external_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('connector_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_items', to='connectors.connectoraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='PlannerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='My Plan', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='PlannerItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_status', models.CharField(choices=[('planned', 'planned'), ('in_progress', 'in_progress'), ('done', 'done'), ('deferred', 'deferred')], default='planned', max_length=30)),
                ('planned_order', models.IntegerField(default=0)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_planned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_states', to='planner.planneritem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_states', to='planner.plannerplan')),
            ],
        ),
        migrations.AddIndex(
            model_name='planneritem',
            index=models.Index(fields=['workspace', 'source', 'source_entity_id'], name='planner_pla_workspa_5f59e7_idx'),
        ),
        migrations.AddIndex(
            model_name='planneritem',
            index=models.Index(fields=['workspace', 'connector_account', 'source_entity_id'], name='planner_pla_workspa_83e1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='planneritem',
            index=models.Index(fields=['workspace', 'last_synced_at'], name='planner_pla_workspa_b4464d_idx'),
        ),
        migrations.AddConstraint(
            model_name='planneritem',
            constraint=models.UniqueConstraint(fields=('workspace', 'connector_account', 'source', 'source_entity_id'), name='planner_item_unique_source'),
        ),
        migrations.AddIndex(
            model_name='plannerplan',
            index=models.Index(fields=['workspace', 'user'], name='planner_pla_workspa_c844d9_idx'),
        ),
        migrations.AddIndex(
            model_name='planneritemstate',
            index=models.Index(fields=['plan', 'planned_order'], name='planner_pla_plan_id_0f2ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='planneritemstate',
            index=models.Index(fields=['plan', 'planned_status'], name='planner_pla_plan_id_a433fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='planneritemstate',
            constraint=models.UniqueConstraint(fields=('plan', 'item'), name='planner_item_state_unique'),
        ),
    ]
