# Generated by Django 5.2.11 on 2026-03-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planneritemstate',
            name='planner_status',
            field=models.CharField(choices=[('inbox', 'inbox'), ('backlog', 'backlog'), ('doing', 'doing'), ('done', 'done')], default='inbox', max_length=20),
        ),
        migrations.AddIndex(
            model_name='planneritemstate',
            index=models.Index(fields=['plan', 'planner_status'], name='planner_pla_plan_id_647886_idx'),
        ),
    ]
