# Generated by Django 5.2.11 on 2026-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_planneritemstate_planner_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planneritemstate',
            name='external_status_requested',
            field=models.CharField(blank=True, choices=[('inbox', 'inbox'), ('backlog', 'backlog'), ('doing', 'doing'), ('done', 'done')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='planneritemstate',
            name='last_writeback_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planneritemstate',
            name='last_writeback_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planneritemstate',
            name='last_writeback_job_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planneritemstate',
            name='last_writeback_succeeded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planneritemstate',
            name='writeback_status',
            field=models.CharField(choices=[('none', 'none'), ('pending', 'pending'), ('synced', 'synced'), ('failed', 'failed'), ('unsupported', 'unsupported')], default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='planneritemstate',
            index=models.Index(fields=['plan', 'writeback_status'], name='planner_pla_plan_id_908071_idx'),
        ),
    ]
