# Generated by Django 5.2.11 on 2026-04-16 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0006_alter_connectoraccount_source'),
        ('ingestion', '0004_jobattempt_job_idempotency_key_job_lease_expires_at_and_more'),
        ('planner', '0003_planneritemstate_external_status_requested_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerStatusIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_planner_status', models.CharField(choices=[('inbox', 'inbox'), ('backlog', 'backlog'), ('doing', 'doing'), ('done', 'done')], max_length=20)),
                ('provider_status_at_request', models.CharField(blank=True, max_length=100)),
                ('provider_completed_at_request', models.BooleanField(default=False)),
                ('resolved_provider_status', models.CharField(blank=True, max_length=100)),
                ('resolved_external_completed', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('synced', 'synced'), ('failed', 'failed'), ('unsupported', 'unsupported'), ('stale', 'stale')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connector_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_status_intents', to='connectors.connectoraccount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_intents', to='planner.planneritem')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_status_intents', to='ingestion.job')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_intents', to='planner.plannerplan')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_intents', to='planner.planneritemstate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status', 'requested_at'], name='planner_pla_workspa_058b2e_idx'), models.Index(fields=['plan', 'item', 'status'], name='planner_pla_plan_id_839b12_idx'), models.Index(fields=['job'], name='planner_pla_job_id_5781ea_idx')],
            },
        ),
    ]
