# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_plannerstatusintent"),
    ]

    operations = [
        migrations.AddField(
            model_name="planneritem",
            name="description_external_requested",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="planneritem",
            name="description_writeback_status",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("pending", "pending"),
                    ("synced", "synced"),
                    ("failed", "failed"),
                    ("unsupported", "unsupported"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="planneritem",
            name="last_description_writeback_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planneritem",
            name="last_description_writeback_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="planneritem",
            name="last_description_writeback_job_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planneritem",
            name="last_description_writeback_succeeded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planneritem",
            name="source_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="planneritem",
            index=models.Index(
                fields=["workspace", "source_created_at"],
                name="planner_pla_workspa_bb62e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planneritem",
            index=models.Index(
                fields=["workspace", "description_writeback_status"],
                name="planner_pla_workspa_51e938_idx",
            ),
        ),
    ]
