# Generated by Django 5.2.11 on 2026-08-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_planneritem_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planneritem',
            name='source',
            field=models.CharField(choices=[('google_fit', 'Google Fit'), ('asana', 'Asana'), ('todoist', 'Todoist'), ('habitica', 'Habitica'), ('jira', 'Jira'), ('github', 'GitHub Issues'), ('linear', 'Linear'), ('clickup', 'ClickUp'), ('trello', 'Trello')], max_length=50),
        ),
    ]
