# Generated by Django 5.2.11 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_alter_planneritem_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planneritem",
            name="source",
            field=models.CharField(
                choices=[
                    ("google_fit", "Google Fit"),
                    ("asana", "Asana"),
                    ("todoist", "Todoist"),
                    ("habitica", "Habitica"),
                    ("jira", "Jira"),
                    ("github", "GitHub Issues"),
                    ("linear", "Linear"),
                    ("clickup", "ClickUp"),
                    ("trello", "Trello"),
                    ("manual", "Personal"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="planneritemstate",
            name="collection",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="planneritemstate",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planneritemstate",
            name="estimated_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
