# Generated by Django 5.x
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConnectorAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("google_fit", "Google Fit"),
                            ("asana", "Asana"),
                            ("todoist", "Todoist"),
                            ("habitica", "Habitica"),
                        ],
                        max_length=50,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("api_token", "API Token"), ("oauth", "OAuth")],
                        max_length=20,
                    ),
                ),
                (
                    "credentials",
                    models.TextField(
                        help_text="Encrypted JSON payload when ENCRYPTION_KEY is set."
                    ),
                ),
                ("credentials_encrypted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["source", "is_active"], name="connectors_source_6e6b0c_idx")],
            },
        ),
    ]
