# Generated by Django 5.x
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectoraccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("disconnected", "Disconnected"),
                    ("connecting", "Connecting"),
                    ("connected", "Connected"),
                    ("error", "Error"),
                ],
                default="disconnected",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="connectoraccount",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectoraccount",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
