# Generated by Django 5.2.11 on 2026-02-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='connectoraccount',
            new_name='connectors__workspa_959e7b_idx',
            old_name='connectors_workspace_source_active_idx',
        ),
    ]
