# Generated by Django 5.2.11 on 2026-02-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_connectoraccount_status_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='connectoraccount',
            new_name='connectors__source_a38b6c_idx',
            old_name='connectors_source_6e6b0c_idx',
        ),
    ]
