# Generated by Django 5.2.11 on 2026-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0008_alter_connectoraccount_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectoraccount',
            name='last_full_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectoraccount',
            name='last_incremental_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectoraccount',
            name='sync_cursor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
