# Generated by Django 5.x
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("google_fit", "Google Fit"),
                            ("asana", "Asana"),
                            ("todoist", "Todoist"),
                            ("habitica", "Habitica"),
                        ],
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["source", "started_at"], name="ingestion_source_f7b48c_idx")],
            },
        ),
    ]
