# Generated by Django 5.2.11 on 2026-02-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='syncrun',
            new_name='ingestion_s_source_552106_idx',
            old_name='ingestion_source_f7b48c_idx',
        ),
    ]
