# Generated by Django 5.2.11 on 2026-02-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='ingestion_j_status_acad6c_idx',
            old_name='ingestion_status_next_run_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='ingestion_j_workspa_e8c4d5_idx',
            old_name='ingestion_workspace_status_queued_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='ingestion_j_workspa_6b1558_idx',
            old_name='ingestion_workspace_job_type_queued_idx',
        ),
    ]
