# Generated by Django 5.2.11 on 2026-02-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rename_ingestion_status_next_run_idx_ingestion_j_status_acad6c_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='ingestion_j_workspa_31e12a_idx',
            old_name='ingestion_workspace_connector_status_idx',
        ),
    ]
