# Generated by Django 5.2.11 on 2026-04-16 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0006_alter_connectoraccount_source'),
        ('ingestion', '0003_rename_ingestion_workspace_connector_status_idx_ingestion_j_workspa_31e12a_idx'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.IntegerField()),
                ('worker_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('retrying', 'retrying')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['idempotency_key', 'status'], name='ingestion_j_idempot_e8b6da_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'lease_expires_at'], name='ingestion_j_status_c5c047_idx'),
        ),
        migrations.AddField(
            model_name='jobattempt',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ingestion.job'),
        ),
        migrations.AddIndex(
            model_name='jobattempt',
            index=models.Index(fields=['job', 'attempt_number'], name='ingestion_j_job_id_20d42f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobattempt',
            index=models.Index(fields=['status', 'started_at'], name='ingestion_j_status_43ce7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobattempt',
            constraint=models.UniqueConstraint(fields=('job', 'attempt_number'), name='job_attempt_unique_attempt_number'),
        ),
    ]
