# Generated by Django 5.2.11 on 2026-08-11 17:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_jobattempt_job_idempotency_key_job_lease_expires_at_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRefreshPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_refresh_enabled', models.BooleanField(default=True)),
                ('refreshes_per_day', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(96)])),
                ('full_refresh_interval_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('cache_version', models.PositiveBigIntegerField(default=1)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_policy', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
