# Generated by Django 5.x
from __future__ import annotations

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("google_fit", "Google Fit"),
                            ("asana", "Asana"),
                            ("todoist", "Todoist"),
                            ("habitica", "Habitica"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_entity_type", models.CharField(max_length=100)),
                ("source_entity_id", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("metric_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "metric_value",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                ("metric_unit", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("raw", models.JSONField()),
                ("dedupe_hash", models.CharField(max_length=64)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["source", "source_entity_id"], name="events_source_2bb817_idx"),
                    models.Index(fields=["start_time"], name="events_start_5b9c14_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "dedupe_hash"), name="unique_event_dedupe"
                    )
                ],
            },
        ),
    ]
