# Generated by Django 5.2.11 on 2026-02-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_source_42f05c_idx',
            old_name='events_source_2bb817_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_start_t_c2d277_idx',
            old_name='events_start_5b9c14_idx',
        ),
    ]
