# Generated by Django 5.2.11 on 2026-02-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_workspa_78d99e_idx',
            old_name='events_workspace_source_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_workspa_677642_idx',
            old_name='events_workspace_start_time_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_workspa_132821_idx',
            old_name='events_workspace_created_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_workspa_3f893a_idx',
            old_name='events_workspace_source_created_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_workspa_9f1693_idx',
            old_name='events_workspace_source_dedupe_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('google_fit', 'Google Fit'), ('asana', 'Asana'), ('todoist', 'Todoist'), ('habitica', 'Habitica')], max_length=50),
        ),
    ]
