# Generated by Django 5.2.11 on 2026-03-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('google_fit', 'Google Fit'), ('asana', 'Asana'), ('todoist', 'Todoist'), ('habitica', 'Habitica'), ('jira', 'Jira')], max_length=50),
        ),
    ]
