# Generated by Django 5.2.11 on 2026-02-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_connector_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_workspa_528680_idx',
            old_name='events_workspa_9ae6d0_idx',
        ),
    ]
