# Generated by Django 5.2.11 on 2026-08-07 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0006_alter_planneritem_source'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='New conversation', max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_chat_threads', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('model', models.CharField(blank=True, max_length=160)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='intelligence.chatthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rules', 'Rules applied'), ('ready', 'AI enriched'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('task_type', models.CharField(blank=True, max_length=64)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('energy', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=12)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('backend', models.CharField(blank=True, max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_analysis', to='planner.planneritem')),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100)),
                ('kind', models.CharField(choices=[('domain', 'Domain'), ('work_type', 'Work type'), ('skill', 'Skill'), ('context', 'Context'), ('priority', 'Priority'), ('other', 'Other')], default='other', max_length=20)),
                ('color', models.CharField(default='#477a64', max_length=16)),
                ('is_system', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_tags', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('rule', 'Rule'), ('ai', 'AI'), ('manual', 'Manual')], max_length=12)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('evidence', models.CharField(blank=True, max_length=280)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='planner.planneritem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='intelligence.unifiedtag')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.CharField(choices=[('openai_responses', 'OpenAI Responses / Codex Luna'), ('openai_compatible', 'OpenAI-compatible local model (Qwen)')], default='openai_responses', max_length=32)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('base_url', models.URLField(blank=True)),
                ('encrypted_api_key', models.BinaryField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['workspace', 'user', '-updated_at'], name='intelligenc_workspa_6b94f7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='intelligenc_thread__fe3335_idx'),
        ),
        migrations.AddIndex(
            model_name='taskanalysis',
            index=models.Index(fields=['status', 'analyzed_at'], name='intelligenc_status_606461_idx'),
        ),
        migrations.AddIndex(
            model_name='taskanalysis',
            index=models.Index(fields=['task_type'], name='intelligenc_task_ty_289123_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedtag',
            index=models.Index(fields=['workspace', 'kind', 'name'], name='intelligenc_workspa_b09e43_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedtag',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='intelligence_tag_workspace_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['item', 'source'], name='intelligenc_item_id_9d9fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['tag', 'source'], name='intelligenc_tag_id_6379ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasktag',
            constraint=models.UniqueConstraint(fields=('item', 'tag'), name='intelligence_task_tag_unique'),
        ),
    ]
