# Generated by Django 5.2.11 on 2026-08-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceaisettings',
            name='backend',
            field=models.CharField(choices=[('openai_responses', 'OpenAI Responses / GPT-5.6 Luna'), ('openai_compatible', 'OpenAI-compatible local model (Qwen)')], default='openai_responses', max_length=32),
        ),
    ]
